#!/usr/bin/env python3
"""Ammonia Plant Builder Agent — Pre-Build Research and Enhancement Plan.
Body PDF generator (ReportLab). Cover generated separately via html2poster.js
and merged with pypdf. English document: FreeSerif body, TOC via TocDocTemplate
+ multiBuild, charts embedded as PNG block flowables.
"""
import os
import sys
import hashlib

PDF_SKILL_DIR = '/home/z/my-project/skills/pdf'
sys.path.insert(0, os.path.join(PDF_SKILL_DIR, 'scripts'))

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch, mm
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY, TA_RIGHT
from reportlab.lib.styles import ParagraphStyle
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase.pdfmetrics import registerFontFamily, stringWidth
from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer, Table,
                                TableStyle, PageBreak, Image, KeepTogether,
                                CondPageBreak, HRFlowable, Flowable)
from reportlab.platypus.tableofcontents import TableOfContents
from PIL import Image as PILImage

# ── Fonts ───────────────────────────────────────────────────────────────────
FONT_DIR = '/usr/share/fonts'
pdfmetrics.registerFont(TTFont('NotoSerifSC', f'{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Regular.ttf'))
pdfmetrics.registerFont(TTFont('NotoSerifSC-Bold', f'{FONT_DIR}/truetype/noto-serif-sc/NotoSerifSC-Bold.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif', f'{FONT_DIR}/truetype/freefont/FreeSerif.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-Bold', f'{FONT_DIR}/truetype/freefont/FreeSerifBold.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-Italic', f'{FONT_DIR}/truetype/freefont/FreeSerifItalic.ttf'))
pdfmetrics.registerFont(TTFont('FreeSerif-BoldItalic', f'{FONT_DIR}/truetype/freefont/FreeSerifBoldItalic.ttf'))
pdfmetrics.registerFont(TTFont('DejaVuSans', f'{FONT_DIR}/truetype/dejavu/DejaVuSansMono.ttf'))
registerFontFamily('NotoSerifSC', normal='NotoSerifSC', bold='NotoSerifSC-Bold')
registerFontFamily('FreeSerif', normal='FreeSerif', bold='FreeSerif-Bold',
                   italic='FreeSerif-Italic', boldItalic='FreeSerif-BoldItalic')
registerFontFamily('DejaVuSans', normal='DejaVuSans', bold='DejaVuSans')

from pdf import install_font_fallback
install_font_fallback()

# ━━ Cascade Palette (auto-generated by design_engine.py palette-cascade) ━━
PAGE_BG       = colors.HexColor('#f4f5f5')
SECTION_BG    = colors.HexColor('#f0f1f2')
CARD_BG       = colors.HexColor('#e8eaeb')
TABLE_STRIPE  = colors.HexColor('#ebeded')
HEADER_FILL   = colors.HexColor('#32454e')
COVER_BLOCK   = colors.HexColor('#566a74')
BORDER        = colors.HexColor('#acbdc5')
ICON          = colors.HexColor('#4b86a4')
ACCENT        = colors.HexColor('#1f6c92')
ACCENT_2      = colors.HexColor('#c23a50')
TEXT_PRIMARY  = colors.HexColor('#131515')
TEXT_MUTED    = colors.HexColor('#747b7e')
SEM_SUCCESS   = colors.HexColor('#529067')
SEM_WARNING   = colors.HexColor('#8c7443')
SEM_ERROR     = colors.HexColor('#a25b54')

TABLE_HEADER_COLOR = HEADER_FILL
TABLE_ROW_EVEN     = colors.white
TABLE_ROW_ODD      = TABLE_STRIPE

# ── Page geometry ───────────────────────────────────────────────────────────
MARGIN = 0.9 * inch
PAGE_W, PAGE_H = A4
AVAIL_W = PAGE_W - 2 * MARGIN
AVAIL_H = PAGE_H - 2 * MARGIN
H1_ORPHAN = AVAIL_H * 0.25

OUT_BODY = '/home/z/my-project/scripts/body.pdf'
ASSETS = '/home/z/my-project/scripts/assets'

DOC_TITLE = 'Ammonia Plant Builder Agent — Pre-Build Research and Enhancement Plan'
DOC_FOOTER_LEFT = 'Prepared for Daemon · KNUST Chemical Engineering'

# ── Styles ──────────────────────────────────────────────────────────────────
S = {}
S['body'] = ParagraphStyle('Body', fontName='FreeSerif', fontSize=10.5,
                           leading=17, alignment=TA_JUSTIFY,
                           textColor=TEXT_PRIMARY, spaceBefore=0, spaceAfter=10)
S['lead'] = ParagraphStyle('Lead', parent=S['body'], fontSize=11.5, leading=19,
                           textColor=HEADER_FILL, spaceAfter=12)
S['h1'] = ParagraphStyle('H1', fontName='FreeSerif', fontSize=22, leading=27,
                         textColor=HEADER_FILL, spaceBefore=18, spaceAfter=4)
S['h2'] = ParagraphStyle('H2', fontName='FreeSerif', fontSize=15, leading=20,
                         textColor=TEXT_PRIMARY, spaceBefore=16, spaceAfter=8)
S['h3'] = ParagraphStyle('H3', fontName='FreeSerif', fontSize=11.5, leading=16,
                         textColor=HEADER_FILL, spaceBefore=12, spaceAfter=6)
S['bullet'] = ParagraphStyle('Bullet', parent=S['body'], alignment=TA_LEFT,
                             leftIndent=16, bulletIndent=4, spaceAfter=6)
S['caption'] = ParagraphStyle('Caption', fontName='FreeSerif', fontSize=8.5,
                              leading=12, alignment=TA_CENTER,
                              textColor=TEXT_MUTED, spaceBefore=3, spaceAfter=6)
S['quote'] = ParagraphStyle('Quote', fontName='FreeSerif-Italic', fontSize=10.5,
                            leading=17, alignment=TA_LEFT, leftIndent=24,
                            textColor=HEADER_FILL, spaceBefore=8, spaceAfter=8,
                            borderPadding=(4, 8, 4, 8))
S['cell'] = ParagraphStyle('Cell', fontName='FreeSerif', fontSize=9, leading=12.5,
                           alignment=TA_LEFT, textColor=TEXT_PRIMARY,
                           wordWrap='CJK')
S['cellc'] = ParagraphStyle('CellC', parent=S['cell'], alignment=TA_CENTER)
S['cellh'] = ParagraphStyle('CellH', fontName='FreeSerif', fontSize=9.2,
                            leading=12.5, alignment=TA_CENTER,
                            textColor=colors.white)
S['code'] = ParagraphStyle('Code', fontName='DejaVuSans', fontSize=8.5,
                           leading=12, alignment=TA_LEFT,
                           textColor=HEADER_FILL)
S['toc_title'] = ParagraphStyle('TocTitle', fontName='FreeSerif', fontSize=22,
                                leading=28, textColor=HEADER_FILL, spaceAfter=18)
S['callout'] = ParagraphStyle('Callout', fontName='FreeSerif', fontSize=10.5,
                              leading=16.5, alignment=TA_LEFT,
                              textColor=HEADER_FILL)

toc_l0 = ParagraphStyle('TOC0', fontName='FreeSerif', fontSize=11.5, leading=20,
                        leftIndent=6, textColor=TEXT_PRIMARY)
toc_l1 = ParagraphStyle('TOC1', fontName='FreeSerif', fontSize=9.5, leading=15,
                        leftIndent=26, textColor=TEXT_MUTED)

# ── Doc template with TOC support + body-start marker ──────────────────────
class BodyStartMarker(Flowable):
    """Invisible marker that records the page where the body (Chapter 1) begins."""
    def __init__(self):
        Flowable.__init__(self)
        self.width = 0
        self.height = 0

    def draw(self):
        self.canv._doctemplate._body_start_page = self.canv.getPageNumber()


class TocDocTemplate(SimpleDocTemplate):
    def afterFlowable(self, flowable):
        if hasattr(flowable, 'bookmark_name'):
            level = getattr(flowable, 'bookmark_level', 0)
            text = getattr(flowable, 'bookmark_text', '')
            key = getattr(flowable, 'bookmark_key', '')
            self.notify('TOCEntry', (level, text, self.page, key))


ROMAN = {1: 'i', 2: 'ii', 3: 'iii', 4: 'iv', 5: 'v', 6: 'vi', 7: 'vii',
         8: 'viii', 9: 'ix', 10: 'x'}


def page_decorations(canvas, doc):
    canvas.saveState()
    # Header: title left + accent rule
    canvas.setFont('FreeSerif', 7.5)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(MARGIN, PAGE_H - 0.55 * inch, DOC_TITLE)
    canvas.setStrokeColor(ACCENT)
    canvas.setLineWidth(1.2)
    canvas.line(MARGIN, PAGE_H - 0.62 * inch, PAGE_W - MARGIN, PAGE_H - 0.62 * inch)
    # Footer: author left + page number right, light rule above
    canvas.setStrokeColor(BORDER)
    canvas.setLineWidth(0.5)
    canvas.line(MARGIN, 0.62 * inch, PAGE_W - MARGIN, 0.62 * inch)
    canvas.setFont('FreeSerif', 7.5)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(MARGIN, 0.45 * inch, DOC_FOOTER_LEFT)
    body_start = getattr(doc, '_body_start_page', None)
    if body_start is None or canvas.getPageNumber() < body_start:
        num = ROMAN.get(canvas.getPageNumber(), str(canvas.getPageNumber()))
    else:
        num = str(canvas.getPageNumber() - body_start + 1)
    canvas.drawRightString(PAGE_W - MARGIN, 0.45 * inch, num)
    canvas.restoreState()


# ── Helpers ─────────────────────────────────────────────────────────────────
story = []


def _glue(text):
    """Glue em-dashes to the preceding word so lines never start with a dash."""
    return text.replace(' \u2014 ', '\u00a0\u2014 ')


def add_heading(text, style, level=0):
    key = 'h_%s' % hashlib.md5(text.encode()).hexdigest()[:8]
    p = Paragraph('<a name="%s"/><b>%s</b>' % (key, text), style)
    p.bookmark_name = key
    p.bookmark_level = level
    p.bookmark_text = text
    p.bookmark_key = key
    return p


def H1(text):
    story.append(CondPageBreak(H1_ORPHAN))
    story.append(Spacer(1, 6))
    story.append(add_heading(text, S['h1'], level=0))
    story.append(HRFlowable(width='100%', color=ACCENT, thickness=1.6,
                            spaceBefore=2, spaceAfter=12))


def H2(text):
    story.append(add_heading(text, S['h2'], level=1))


def H3(text):
    story.append(Paragraph('<b>%s</b>' % text, S['h3']))


def P(text, style='body'):
    story.append(Paragraph(_glue(text), S[style]))


def B(text):
    story.append(Paragraph(_glue(text), S['bullet'], bulletText='•'))


def NUM(i, text):
    story.append(Paragraph(_glue(text), S['bullet'], bulletText='%d.' % i))


def CAL(text):
    """Callout box: accent left border + light tint background."""
    inner = Paragraph(_glue(text), S['callout'])
    box = Table([[inner]], colWidths=[AVAIL_W])
    box.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), SECTION_BG),
        ('LINEBEFORE', (0, 0), (0, -1), 3, ACCENT),
        ('LEFTPADDING', (0, 0), (-1, -1), 12),
        ('RIGHTPADDING', (0, 0), (-1, -1), 10),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]))
    story.append(Spacer(1, 6))
    story.append(box)
    story.append(Spacer(1, 10))


def TBL(headers, rows, ratios, caption=None, font_size=9, align_map=None):
    """Table with Paragraph-wrapped cells, palette colors, centered."""
    assert abs(sum(ratios) - 1.0) < 1e-6, 'ratios must sum to 1'
    col_w = [r * AVAIL_W for r in ratios]
    hstyle = ParagraphStyle('h_tmp', parent=S['cellh'], fontSize=font_size + 0.2)
    cstyle = ParagraphStyle('c_tmp', parent=S['cell'], fontSize=font_size)
    ccstyle = ParagraphStyle('cc_tmp', parent=S['cellc'], fontSize=font_size)
    align_map = align_map or {}
    data = [[Paragraph('<b>%s</b>' % h, hstyle) for h in headers]]
    for row in rows:
        cells = []
        for j, cell in enumerate(row):
            st = ccstyle if align_map.get(j) == 'c' else cstyle
            cells.append(Paragraph(_glue(cell), st))
        data.append(cells)
    t = Table(data, colWidths=col_w, hAlign='CENTER', repeatRows=1)
    style_cmds = [
        ('BACKGROUND', (0, 0), (-1, 0), TABLE_HEADER_COLOR),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('GRID', (0, 0), (-1, -1), 0.4, BORDER),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
    ]
    for i in range(1, len(data)):
        bg = TABLE_ROW_ODD if i % 2 == 0 else TABLE_ROW_EVEN
        style_cmds.append(('BACKGROUND', (0, i), (-1, i), bg))
    t.setStyle(TableStyle(style_cmds))
    story.append(Spacer(1, 8))
    if caption:
        cap = Paragraph(caption, S['caption'])
        if len(rows) <= 12:
            story.append(KeepTogether([t, cap]))
        else:
            story.append(t)
            story.append(cap)
    else:
        story.append(t)
    story.append(Spacer(1, 10))


def CHART(filename, caption, max_h=270):
    path = os.path.join(ASSETS, filename)
    pil = PILImage.open(path)
    ow, oh = pil.size
    ratio = min(AVAIL_W / ow, max_h / oh, 1.0)
    img = Image(path, width=ow * ratio, height=oh * ratio)
    cap = Paragraph(caption, S['caption'])
    story.append(Spacer(1, 14))
    story.append(KeepTogether([img, cap]))
    story.append(Spacer(1, 14))


def CODE(lines):
    """Code/formula block: monospace, accent left border."""
    paras = [Paragraph(ln, S['code']) for ln in lines]
    box = Table([[paras]], colWidths=[AVAIL_W])
    box.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), SECTION_BG),
        ('LINEBEFORE', (0, 0), (0, -1), 2, ACCENT),
        ('LEFTPADDING', (0, 0), (-1, -1), 12),
        ('RIGHTPADDING', (0, 0), (-1, -1), 10),
        ('TOPPADDING', (0, 0), (-1, -1), 7),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 7),
    ]))
    story.append(Spacer(1, 6))
    story.append(box)
    story.append(Spacer(1, 10))


# ═════════════════════════════════════════════════════════════════════════════
# TABLE OF CONTENTS (front matter — roman numbering)
# ═════════════════════════════════════════════════════════════════════════════
toc = TableOfContents()
toc.levelStyles = [toc_l0, toc_l1]
story.append(Paragraph('<b>Table of Contents</b>', S['toc_title']))
story.append(HRFlowable(width='100%', color=ACCENT, thickness=1.6,
                        spaceBefore=0, spaceAfter=14))
story.append(toc)
story.append(PageBreak())
story.append(BodyStartMarker())

# ═════════════════════════════════════════════════════════════════════════════
# CONTENT CHAPTERS
# ═════════════════════════════════════════════════════════════════════════════

# ── Chapter 1: Executive Summary and Verdict ────────────────────────────────
H1('1. Executive Summary and Verdict')

P('This dossier is the pre-build research pass over the ammonia plant builder agent plan. '
  'It stress-tests the architecture, maps the competitive landscape, hardens the engineering '
  'layer with verified correlations and data, explores how far the interactivity can be pushed, '
  'and re-cuts the roadmap with realistic effort estimates. Every claim in this document traces '
  'to either a live web source found during research (August 2026) or a published engineering '
  'reference; the full source library is ranked in Chapter 9.', 'lead')

H2('1.1 The verdict on the current plan')
P('The plan\u2019s central bet is correct, and it is worth saying plainly: <b>the physics/language '
  'separation is the right architecture, and it is exactly where the industry is heading.</b> '
  'GSE Solutions, the largest operator-training-simulator vendor, announced a 2026 collaboration '
  'with Nuclearn to author training scenarios from natural-language prompts on top of deterministic '
  'simulation — the same LLM-as-parameterizer, engine-as-calculator pattern the plan describes. '
  'Siemens shipped a natural-language copilot inside NX CAD in 2025. OpenAI\u2019s structured '
  'outputs feature reports 100% JSON-schema adherence versus roughly 40% for prompt-only JSON, '
  'which validates the plan\u2019s decision to make intake a single constrained extraction call '
  'rather than a free-form agent loop. The plan is not just defensible; it is early.')

P('The scope narrowing to ammonia only is also confirmed as the right call. Research found no '
  'free, full-flowsheet ammonia simulator anywhere — not in education, not in open source, not '
  'from vendors. The closest free artifact is a Flash-era equilibrium toy from Annenberg Learner. '
  'A bounded nine-unit-operation library that models the complete natural-gas-to-NH<sub>3</sub> '
  'train would be the first of its kind, positioned in front of a documented demand wave: the '
  'green-ammonia build-out and a workforce gap measured in tens of thousands of workers by 2030.')

H2('1.2 Five corrections to make before writing code')
P('The stress test in Chapter 2 surfaces issues that would cost real credibility if discovered '
  'later by a reviewing engineer. None of them changes the architecture; all of them change the '
  'first month of implementation.')

TBL(
    ['#', 'Correction', 'Why it matters'],
    [
        ['C1', 'Converter approach-to-equilibrium is 90\u201395% per bed, not the 60\u201370% the plan assumes. Industry design convention (Cheema and Krewer 2018; Topsoe/Casale practice) holds each bed outlet at 90\u201395% of equilibrium. At 0.65 the model under-predicts converter outlet NH<sub>3</sub> by 3\u20135 percentage points.',
         'The synthesis loop is the flagship of the whole plant; its numbers must survive an engineer\u2019s scrutiny on first demo.'],
        ['C2', 'Neither CoolProp nor Cantera can compute the NH<sub>3</sub>\u2013H<sub>2</sub>\u2013N<sub>2</sub>\u2013CH<sub>4</sub>\u2013Ar flash at \u221220 \u00b0C and 150 bar. CoolProp\u2019s mixture framework is GERG-style and NH<sub>3</sub> is not a GERG component; Cantera has no real-fluid liquid flash. Use the <i>thermo</i> library (MIT) with Peng\u2013Robinson and binary interaction parameters.',
         'The plan currently cites Cantera/CoolProp for thermophysics; the condenser model would be built on a library that cannot do its job.'],
        ['C3', 'Model the secondary reformer as two zones: adiabatic combustion of process air, then catalytic equilibrium. Air flow is the degree of freedom that sets H<sub>2</sub>/N<sub>2</sub> = 3.',
         'A single equilibrium block cannot close the nitrogen balance, and the nitrogen balance defines the plant.'],
        ['C4', 'Carry argon explicitly (0.93% of air) through the whole flowsheet.',
         'Purge sizing and loop inert levels (10\u201315 mol%) depend entirely on Ar; dropping it breaks the purge story.'],
        ['C5', 'Validate against EFMA, Fl\u00f3rez-Orrego (2017), the 2024 TAMU thesis and the Rice CENG403 design projects. Turton and Felder contain no ammonia case study; "Temperley" does not exist; "Maxwell\u2019s thesis" is unverifiable.',
         'The validation anchors named in the plan will not actually validate an ammonia plant.'],
    ],
    [0.06, 0.52, 0.42],
    caption='Table 1.1 — The five must-fix corrections, in the order they should be applied.',
    font_size=8.8)

H2('1.3 The position this product can own')
P('Chapter 3 maps the terrain: commercial simulators sit behind a $10k\u2013100k/year cost wall, '
  'free simulators have no pedagogy, AI copilots are text-only and professional-priced, and '
  'industrial operator training costs $800k\u2013$3M per installation. The verified white space is '
  'the intersection nobody occupies:')

CAL('<b>The free, voice-narrated, OTS-style ammonia plant trainer.</b> One deeply modeled plant, '
    'explained out loud, recomputed live for every question a student asks, exportable as a real '
    'mass balance. Mechanics are commoditized; nobody owns pedagogy + voice + ammonia + 3D together.')

P('The headline numbers behind that position, all sourced in later chapters:')

TBL(
    ['Number', 'Value', 'Source chapter'],
    [
        ['Commercial simulator license wall', '$10,000\u2013$100,000+ / year', 'Ch. 3'],
        ['Industrial OTS installation cost', '$800,000\u2013$3,000,000', 'Ch. 3'],
        ['Existing free ammonia simulators', '1 (equilibrium-only toy)', 'Ch. 3'],
        ['Narration TTS cost, 100 walkthroughs', '$4.50 \u2014 or $0 on Azure free tier', 'Ch. 6'],
        ['Achievable what-if voice latency', '0.4\u20130.5 s chunked; 0.5\u20130.8 s full-duplex', 'Ch. 5'],
        ['BAT specific energy, SMR ammonia', '28\u201329 GJ/t NH<sub>3</sub>', 'Ch. 4'],
        ['Solo build, part-time, to v3 operator mode', '\u224822 working weeks', 'Ch. 8'],
    ],
    [0.44, 0.36, 0.20],
    caption='Table 1.2 — Headline research numbers.',
    font_size=9)

P('The single most important strategic finding, echoing and sharpening the plan\u2019s own instinct: '
  'the gap between an impressive demo and a credible product is entirely whether the what-if loop '
  'is real. A reviewer\u2019s first test will be to change a number and check whether the plant '
  'recomputes or improvises. Everything in this dossier ultimately serves that test.')

# ── Chapter 2: Stress Test ──────────────────────────────────────────────────
H1('2. Stress Test: Where the Plan Holds and Where It Breaks')

P('This chapter takes the plan\u2019s thirteen sections one by one and asks what survives contact '
  'with evidence. The structure is deliberately asymmetric: strengths get a short confirmation, '
  'problems get the detail, because problems are where pre-build research pays for itself.')

H2('2.1 What the plan gets right')
NUM(1, '<b>The physics/language split.</b> Every adjacent signal validates it: GSE + Nuclearn '
       '(2026) authoring OTS scenarios with LLMs over deterministic simulation; Siemens Design '
       'Copilot in NX; the AutoChemSchematic research agent that verifies DWSIM material balances. '
       'The pattern "LLM emits tool calls, deterministic engine computes, LLM narrates the diff" is '
       'where serious engineering AI converged in 2025\u20132026.')
NUM(2, '<b>Bounded ammonia scope.</b> The library is genuinely finite — roughly a dozen models '
       'including the desulfurizer and circulator the plan omits — and every one has published '
       'operating data behind it (Chapter 4). No competitor has built the free version of any of it.')
NUM(3, '<b>The build order.</b> Testing plumbing with a pure-mass-balance splitter before any '
       'physics, then the closed-form compressor, then once-through reactors, and only then the '
       'recycle loop, is exactly how seven of nine unit operations get validated with plain '
       'sequential math. This de-risks the one genuinely hard numerical problem.')
NUM(4, '<b>Warm-started what-ifs.</b> Correct, and stronger than the plan states: with a good tear '
       'initialization, a small perturbation typically converges in a handful of iterations '
       '(Chapter 4 gives the strategy and the iteration budget), which is what makes a conversational '
       'recompute loop feel instant.')
NUM(5, '<b>Templated narration for structured deltas.</b> Filling a template from real before/after '
       'numbers costs zero LLM calls and cannot hallucinate — this remains one of the sharpest '
       'design decisions in the plan.')

H2('2.2 Seven engineering corrections')
P('Each correction below is stated with its evidence. C1\u2013C5 also appear in the executive '
  'summary; here they are given with the numbers an implementer needs.')

H3('C1 — Converter approach to equilibrium: 0.90\u20130.95, not 0.60\u20130.70')
P('The plan\u2019s "60\u201370% fractional approach" reads like a conservatism choice, but it is '
  'outside industrial design practice. Published converter models hold each bed at 90\u201395% of '
  'equilibrium conversion, or equivalently a temperature approach of 15\u201330 \u00b0C; '
  'Cheema and Krewer\u2019s power-to-ammonia design (RSC Advances, 2018) pins bed outlets at 90% '
  'of the equilibrium temperature, and the Fl\u00f3rez-Orrego industrial model (Energy, 2017) '
  'agrees. At 450 \u00b0C and 200 bar the verified equilibrium is 27.4 mol% NH<sub>3</sub>; '
  'a 0.65 fractional approach predicts 17.8 mol% where industry expects 24.7\u201326.1 mol% — '
  'an error large enough to poison every downstream number in the loop, including product rate, '
  'recycle ratio and purge. Chapter 4\u2019s Figure 4.1 makes the gap visible.')

H3('C2 — The thermophysical library for the condenser is wrong')
P('The plan lists Cantera and CoolProp as the property layer. For reactor equilibrium they are '
  'usable (Cantera\u2019s Gibbs minimization is a good cross-check). For the synthesis-loop '
  'condenser they are not: CoolProp\u2019s mixture framework is a GERG-2008-style multi-fluid '
  'model, NH<sub>3</sub> is not among its supported mixture components (the NH<sub>3</sub>\u2013water '
  'pair is explicitly unavailable, GitHub issue #341), and mixture flashes support only a small '
  'set of pre-generated operations (issue #2534, April 2025). Cantera performs no real-fluid '
  'liquid flash at all. The industry-standard answer for NH<sub>3</sub>-containing loop mixtures '
  'is a cubic equation of state — Peng\u2013Robinson with binary interaction parameters — which '
  'is precisely what Caleb Bell\u2019s <i>thermo</i> library (MIT) provides, in pure Python, with '
  'flash algorithms and mixture enthalpies. Research-grade reference EOS exist for exactly the '
  'loop binaries (Herrmann et al., Fluid Phase Equilibria, 2020) and serve as the validation '
  'target. Recommended split: <i>thermo</i> for the loop VLE and enthalpies, CoolProp for pure '
  'NH<sub>3</sub> and IF97 steam, hand-coded K<sub>p</sub> correlations for reactors.')

H3('C3 — The secondary reformer is two zones, not one equilibrium block')
P('Process air enters the secondary reformer and its oxygen burns hydrogen (fastest consumer) in '
  'an adiabatic combustion zone that lifts the gas to roughly 950\u20131000 \u00b0C; the residual '
  'methane then approaches equilibrium over the catalyst bed, exiting at 0.2\u20130.3% dry CH<sub>4</sub>. '
  'Modeling this as a single equilibrium reactor cannot represent the combustion step, and more '
  'importantly the air flow is the design degree of freedom that fixes the final H<sub>2</sub>/N<sub>2</sub> '
  'ratio at 3 — the specification the whole plant serves. The two-zone recipe with air as DOF is '
  'in Chapter 4, Table 4.2.')

H3('C4 — Argon must be an explicit species')
P('Air brings 0.93% argon. Ar is inert, accumulates in the loop, and together with methane sets '
  'the inert fraction (industry: 10\u201315 mol%) that the purge exists to control. A species set '
  'without Ar produces a loop that never needs its purge — silently breaking one of the most '
  'instructive stories the narrator can tell. The stream schema in Chapter 4 carries nine species '
  'including Ar.')

H3('C5 — Citation hygiene: three anchors do not exist')
P('The plan\u2019s open items mention Gillespie\u2013Beattie (correct — verified below) but the '
  'research also surfaced three phantom references in the surrounding material: "Temperley" is not '
  'a real correlation for ammonia synthesis equilibrium (the lineage is Larson\u2013Dodge, 1923, '
  'then Gillespie\u2013Beattie, 1930, then the textbook tables in Vancini 1971 and Appl 1999); '
  '"Maxwell\u2019s thesis" could not be located in any library or repository; and Turton\u2019s '
  'and Felder\u2019s textbooks, while canonical for process design generally, contain no complete '
  'ammonia-plant case study with a stream table. Validation must anchor on the real sources '
  'ranked in Chapter 9.')

H3('C6 — Gillespie\u2013Beattie needs its pressure-dependent coefficient table')
P('The correlation is the right choice and was numerically re-verified during this research '
  '(classic values reproduce exactly: 16.3% NH<sub>3</sub> at 450 \u00b0C/100 bar; 38.2% at '
  '400 \u00b0C/200 bar; 26.4% at 500 \u00b0C/300 bar). But it is an <i>apparent</i> equilibrium '
  'constant in partial-pressure terms whose coefficients \u03b2 and I are themselves '
  'pressure-dependent — a single pressure-independent formula is wrong across the 100\u2013300 bar '
  'range this plant spans. The full implementation-ready table, units and validity limits are '
  'given in Chapter 4, Section 4.3.')

H3('C7 — Convergence needs a strategy, not just a method')
P('The plan names direct substitution or Wegstein, which is a reasonable start but incomplete. '
  'Wegstein\u2019s acceleration factor must be bounded (commercial simulators clip it to '
  '[\u22125, 0]) or it overshoots and oscillates; the tear stream must be initialized close to the '
  'answer or iterations are wasted and the equilibrium solve can find the trivial no-reaction '
  'root. The hardened recipe — damped direct substitution for three iterations, then bounded '
  'Wegstein, Broyden as the stall fallback, and specific tear initialization values — is '
  'Section 4.4.')

H2('2.3 Architecture gaps the plan does not address')
B('<b>No validation layer between the LLM and the engine.</b> Structured outputs guarantee the '
  'JSON shape, not the values: an LLM can emit 900 bar loop pressure in perfectly valid JSON. '
  'A Pydantic model with hard physical ranges (loop 80\u2013250 bar, S/C 2\u20134, bed '
  'temperatures 350\u2013530 \u00b0C) must reject, retry once with a clarifying question, then '
  'fall back to defaults with a flag. Chapter 6 specifies this pipeline.')
B('<b>No enthalpy reference state or energy-closure plan.</b> Every stream needs a single '
  'consistent enthalpy basis (elements at 298.15 K recommended) or the energy balance will not '
  'close across reactors and the future economics mode is meaningless. The steam system around '
  'the reformer (HP steam at ~100 bar raised in the convection bank and secondary waste-heat '
  'boiler) is half the energy story of a real plant and deserves an explicit model object even '
  'in MVP.')
B('<b>Session and warm-start state is undesigned.</b> The what-if loop\u2019s responsiveness '
  'depends on keeping the last converged solution in memory keyed to the session; the plan implies '
  'this but never states it. It should be a first-class object (last converged tear vector, '
  'parameter set, diff log) so narration can cite before/after numbers.')
B('<b>The fault-parameterization surface is undefined.</b> The v3 operator-training stage needs a '
  'whitelist of faultable parameters (fouling factors, approach values, efficiencies, pressure '
  'drops) with sane ranges — defining it early costs nothing and keeps the engine\u2019s API '
  'stable. Chapter 5 gives the taxonomy.')
B('<b>No regression harness.</b> A golden set of published stream tables (Chapter 9) should '
  'become automated tests from the first week: unit-level checks, then train-level, then the '
  'loop, then whole-plant mass and energy closure to 10<super>\u22126</super> relative.')

H2('2.4 Layer-by-layer scorecard')
TBL(
    ['Layer', 'Plan\u2019s position', 'Grade', 'Required fix'],
    [
        ['Deterministic engine', 'Custom unit ops + sequential-modular solver', 'A\u2212',
         'Apply C1\u2013C7; add enthalpy basis and Ar species'],
        ['Intake (LLM \u2192 JSON)', 'Single-shot extraction, cheap model', 'A',
         'Add strict schema + Pydantic range envelope + retry'],
        ['Base narration', 'Script generated once, read by TTS', 'A\u2212',
         'Sentence-chunked streaming; 60\u201390 s interruptible beats'],
        ['What-if loop', 'Tool-calling agent, warm-started recompute', 'A',
         'Protect the recompute path (Ch. 8 critical path); optimistic UI'],
        ['Diagnosis / rationale', 'LLM grounded in reference material', 'B\u2212',
         'Underspecified: ground in EFMA/Ullmann chunks; bind claims to engine numbers'],
        ['3D render', '\u201c3D render\u201d in MVP', 'B',
         'Define budget: draw calls, tag registry, block-out geometry first'],
        ['TTS layer', 'Piper / OpenAI / ElevenLabs cost table', 'B+',
         'Azure 500k free chars/mo or gpt-4o-mini-tts persona; abstraction over providers'],
        ['Roadmap', 'MVP \u2192 v5 staging', 'A\u2212',
         'Re-scope: validation is a stage, exports before economics; weeks, not vibes'],
    ],
    [0.20, 0.30, 0.08, 0.42],
    caption='Table 2.1 — Scorecard by architectural layer. No layer needs replacing; three need specification work.',
    font_size=8.8, align_map={2: 'c'})

P('The pattern across the scorecard is consistent: the plan\u2019s skeleton is strong, and every '
  'weakness is a missing specification rather than a wrong idea. That is the best possible '
  'pre-build diagnosis — it means the next step is writing details, not rethinking.')


# ── Chapter 3: The Landscape ────────────────────────────────────────────────
H1('3. The Landscape: What Exists, What Is Missing')

P('Before building, it is worth knowing precisely what a chemical engineering student can reach '
  'today, because the answer defines the product\u2019s reason to exist. This chapter maps four '
  'territories — commercial simulators, free engines, AI-native tools, and training simulators — '
  'then states the white space and the threats.')

H2('3.1 The cost wall: commercial simulators')
P('The professional tools are excellent and effectively unreachable for an individual student. '
  'AspenTech\u2019s academic program licenses universities rather than students; a September 2023 '
  'promotion sold students Aspen Plus or HYSYS at $100 for one product in a limited window '
  '(listed value $2,700), which is the closest any incumbent came to direct student access. '
  'Commercial licenses are quote-only and commonly reported between $10,000 and $100,000+ per '
  'year. AVEVA PRO/II, VMGSim (now Honeywell) and Chemstations\u2019 ChemCAD are quote-only or '
  'site-licensed; Honeywell\u2019s UniSim offers 60-day trials. Every one is a Windows desktop '
  'install, usually behind a university VPN or VM. None runs in a browser, none narrates, none '
  'explains itself.')

TBL(
    ['Product', 'Access reality for a student', 'Price signal'],
    [
        ['Aspen Plus / HYSYS', 'Via university site license; occasional $100 promos, one product, limited window', '$10k\u2013$100k+/yr commercial'],
        ['AVEVA PRO/II (SimSci)', 'Quote-only enterprise; no student path', 'undisclosed'],
        ['VMGSim (Honeywell)', 'Quote-only enterprise', 'undisclosed'],
        ['Honeywell UniSim', 'Free 60-day trial, Windows desktop only', 'trial-ware'],
        ['ChemCAD (Datacor)', 'Free only at universities holding site licenses (e.g. UIUC, Alabama webstores)', 'site license'],
        ['MaximaLabs', 'Browser, zero install; free tier for learning, AI copilot included', '$0 / $299/mo teams'],
    ],
    [0.22, 0.48, 0.30],
    caption='Table 3.1 — The accessibility wall. Note MaximaLabs at the bottom: the only browser-native player, and the closest delivery-model comparable.',
    font_size=8.8)

H2('3.2 Free engines: the mechanics are already commoditized')
P('DWSIM is the crown jewel of open-source simulation: GPL-licensed, 35+ unit operations, '
  'steady-state and dynamic modes, CAPE-OPEN compliance, Python scripting, and active development '
  '(DWSIM 10 even ships a patron-preview AI assistant that builds flowsheets from natural-language '
  'commands). IDAES-PSE, the DOE-funded Pyomo framework, is powerful but expert-oriented. COCO, '
  'OMChemSim, NeqSim and ThermoPack round out the ecosystem. The honest question this raises is '
  '"why build a custom engine at all?" — and it deserves an honest answer.')

B('<b>Determinism and narrative control.</b> Every number the narrator speaks must be explainable '
  'at unit-op granularity, in teaching language, on demand. Wrapping DWSIM means wrapping its '
  'property packages, convergence behavior and failure modes in someone else\u2019s vocabulary.')
B('<b>Latency.</b> An interactive what-if loop wants a warm-started solve in tens of milliseconds; '
  'a full .NET flowsheet simulator re-solve is the wrong shape for that, and its recycle '
  'convergence failures are opaque to students.')
B('<b>Licensing and deployment.</b> GPL v3 is workable for a free web app but constrains any '
  'future commercialization; the pythonnet/.NET server stack is fragile to deploy.')
B('<b>The right use for DWSIM is offline:</b> build the same plant in it once and use it as a '
  'validation oracle against the custom engine — a second opinion, not a runtime.')

H2('3.3 The AI wave: research is arriving, products are text-only and pro-priced')
P('Academic work is converging on exactly this product\u2019s shape: "Text-to-flowsheet" (RSC '
  'Digital Discovery, 2026) generates flowsheets from natural language; Sketch2Simulation (AIChE '
  '2026) turns diagrams into HYSYS models; Liang (2026) built an LLM agent for user-friendly '
  'process simulation; AutoChemSchematic (2025) closes the loop by verifying DWSIM balances. On '
  'the product side, MaximaLabs (browser, 60+ unit ops, AI copilot, free tier, $299/mo teams) is '
  'the closest comparable; Alkali\u2019s ProcessMate (YC, 2025) targets professional design and '
  'procurement; DWSIM 10\u2019s AI assistant is a desktop patron preview. An IChemE webinar in '
  'August 2026 pitched an LLM copilot for Aspen Plus in design education. Every single one is '
  'text-first, and none is ammonia-pedagogical, voiced, or free-for-students at full capability.')

H2('3.4 The training-simulator world: what the pros pay')
P('Industrial operator training simulators pair a high-fidelity dynamic model with an emulated '
  'control system, an instructor station that injects malfunctions, and scoring. GSE Solutions '
  'has delivered 173 nuclear, 208 fossil and 114 process simulators since 1971; Honeywell, AVEVA, '
  'Yokogawa and Emerson sell comparable suites. The price of admission is brutal: refinery-scale '
  'OTS installations run $800,000 to $3,000,000, in a market estimated (definitions vary wildly) '
  'between $2.4B and $12.4B and growing near 12% annually. Operator training is an '
  'employer-funded experience; no student can buy in. Meanwhile the free educational layer — '
  'LearnChemE\u2019s 320+ browser simulations from CU Boulder — is excellent but built from '
  'single-concept widgets, with no LLM, no full flowsheet, no voice. The only free ammonia '
  'interactive found anywhere is Annenberg\u2019s "Control a Haber-Bosch Plant," a legacy '
  'equilibrium-only exercise. A peer-reviewed Haber-Bosch teaching module (August 2026) proves '
  'educator demand — while requiring a commercial ChemCAD license.')

H2('3.5 The ammonia demand signal')
P('Ammonia is the hottest molecule in the energy transition: the IEA\u2019s Global Hydrogen Review '
  '2025 counts 200+ committed low-emissions projects with ammonia as the dominant hydrogen '
  'carrier, and analysts project the green-ammonia market growing from a $1.5\u20133.4B base '
  'toward $170B+ by 2035. The workforce signal is concrete: the UK Hydrogen Skills Alliance '
  'needs more than 25,000 hydrogen-sector workers by 2030; South Africa\u2019s skills audit '
  'found 24 required degree programs not yet offered. Students entering this field have no free '
  'interactive tool that teaches an actual ammonia train. That is the audience.')

H2('3.6 White space and threats')
P('Cross-referencing all four territories, six gaps remain unoccupied. Ranked by defensibility:')
B('<b>Voice-native plant simulation.</b> Every AI copilot found is text-based; nobody speaks the '
  'plant aloud or listens for spoken what-ifs.')
B('<b>Free full-flowsheet ammonia simulator</b> (reforming \u2192 shift \u2192 methanation \u2192 '
  'compression \u2192 synthesis loop \u2192 condense \u2192 recycle/purge) — verified absent.')
B('<b>LLM what-if loop on a deterministic engine, free for students</b> — MaximaLabs is '
  'pro-priced; the research prototypes are not deployed.')
B('<b>3D bound to the live solve</b> — published VR plants are static visualizations; none map '
  'real stream data onto equipment as parameters change.')
B('<b>Student-accessible fault injection</b> — OTS-style malfunction training at $0 instead of '
  '$800k+.')
B('<b>Exportable deliverables from a chat session</b> — a real mass-balance table or PFD a '
  'student can submit.')

TBL(
    ['Threat', 'Overlap', 'Verdict'],
    [
        ['DWSIM + DWSIM 10 AI assistant', 'High on engine; zero on pedagogy, voice, 3D, ammonia',
         'Pre-empt the "why not DWSIM?" objection in-app with a one-screen answer; cite it as validation oracle'],
        ['MaximaLabs', 'High on delivery model (browser + AI copilot)', 'Professional focus, $299/mo teams; move fast on the student niche before an edu tier appears'],
        ['LearnChemE (CU Boulder)', 'Same audience, different format', 'Partner or channel, not competitor — single-concept widgets complement a whole-plant sim'],
        ['Alkali ProcessMate (YC 2025)', 'Medium on "AI copilot" mindshare', 'Professional procurement focus; watch for a university pivot'],
        ['AspenTech + academic copilots', 'Capability king; IChemE 2026 copilot-for-education thread', 'Access friction persists; keep an eye on hosted academic tiers'],
    ],
    [0.26, 0.30, 0.44],
    caption='Table 3.2 — Threat model. No incumbent currently moves on voice + ammonia pedagogy + free.',
    font_size=8.8)

CAL('<b>Positioning statement.</b> For chemical engineering students and early-career engineers, '
    'this is the free, voice-narrated ammonia plant you can interrogate: every number recomputed '
    'live, every unit explained out loud, every fault diagnosable — the OTS experience nobody '
    'prices for students, wrapped around one plant modeled deeply enough to check against '
    'published data.')

# ── Chapter 4: The Hardened Engine ─────────────────────────────────────────
H1('4. The Hardened Engine: Correlations, Data, Validation')

P('This chapter resolves the plan\u2019s open items — stream schema, correlations per unit '
  'operation, converter model choice — with implementation-ready numbers. Unless tagged '
  'otherwise, values are sourced from the validation library in Chapter 9; the '
  'Gillespie\u2013Beattie implementation was additionally re-verified numerically during this '
  'research by reproducing the classic equilibrium tables.')

H2('4.1 The stream object, finalized')
TBL(
    ['Field', 'Type', 'Units (internal)', 'Notes'],
    [
        ['id', 'str', '\u2014', 'Stable tag, e.g. S-104 (feeds the PFD/3D tag registry)'],
        ['phase', 'enum', '\u2014', 'vapor / liquid / two-phase marker for the condenser'],
        ['T', 'float', 'K', 'Kelvin internally; display \u00b0C'],
        ['P', 'float', 'Pa', 'Pascals internally; display bar'],
        ['F', 'float', 'kmol/h', 'Molar basis keeps stoichiometry linear'],
        ['y', 'dict', 'mole fractions', '9 species; \u03a3 = 1.0 enforced at 10<super>\u221210</super>'],
    ],
    [0.14, 0.12, 0.22, 0.52],
    caption='Table 4.1 — Stream schema. Species set: H<sub>2</sub>, N<sub>2</sub>, NH<sub>3</sub>, CH<sub>4</sub>, H<sub>2</sub>O, CO, CO<sub>2</sub>, O<sub>2</sub>, Ar.',
    font_size=9)
P('Design rules that prevent whole classes of bugs: store mole fractions only (derive mass flow '
  'on demand — never two sources of truth); fix one enthalpy reference state for the entire '
  'flowsheet (elements at 298.15 K) so reactor duties close; carry units metadata on every '
  'object; keep unit-op derived state (duties, approaches, efficiencies) in unit objects, not '
  'streams. Tolerances: compositions to 10<super>\u221210</super>, flows to 10<super>\u22126</super> '
  'relative.')

H2('4.2 Unit-operation modeling table')
P('The complete first-build recipe, one row per unit operation. "Eq." gives the governing '
  'relation; defaults are the values to hard-code before the first what-if ever runs.')

TBL(
    ['Unit', 'Model', 'Key relations and defaults'],
    [
        ['Feed desulfurization', 'Black box',
         'Pass-through with ZnO polish to below 0.1 ppm S; narrative hook only'],
        ['Primary reformer', 'SR1 + WGS simultaneous equilibrium, ideal-gas K<sub>p</sub>, Dalton\u2019s law',
         'K<sub>SR1</sub> = 1.198\u00d710<super>13</super> e<super>\u221226830/T</super> [bar<super>2</super>]; '
         'K<sub>WGS</sub> = 1.767\u00d710<super>\u22122</super> e<super>4400/T</super>; 25\u201335 bar; S/C = 3.0; '
         'outlet 780\u2013830 \u00b0C; CH<sub>4</sub> approach 5\u201310 \u00b0C; only 30\u201340% of hydrocarbon converts here'],
        ['Secondary reformer', 'Two-zone: adiabatic air combustion, then equilibrium',
         'Combustion of O<sub>2</sub> (burns H<sub>2</sub> first) to ~950\u20131000 \u00b0C; then SR1+WGS to 0.2\u20130.3% dry CH<sub>4</sub>; '
         'air flow = DOF setting H<sub>2</sub>/N<sub>2</sub> = 3; Ar = 0.93% of air'],
        ['HT shift', 'WGS equilibrium + approach',
         'Fe\u2013Cr, inlet ~350\u2013400 \u00b0C; exit ~3% CO dry; approach 10\u201325 \u00b0C'],
        ['LT shift', 'WGS equilibrium + approach',
         'Cu\u2013Zn, 200\u2013220 \u00b0C; exit 0.2\u20130.4% CO dry; approach 15\u201330 \u00b0C'],
        ['CO<sub>2</sub> removal', 'Splitter + duty',
         'Removal 99.5%+; residual 100\u20131000 ppmv CO<sub>2</sub>; reboiler 30\u201360 MJ per kmol CO<sub>2</sub>'],
        ['Methanator', 'Adiabatic equilibrium',
         'Ni catalyst, ~300 \u00b0C inlet; \u0394T = 74 \u00b0C per 1 vol% CO, 60 \u00b0C per 1 vol% CO<sub>2</sub>; exit below 1 ppm carbon oxides'],
        ['Syngas compressor', 'Closed-form polytropic, 3\u20134 stages, intercooled to ~40 \u00b0C',
         '(n\u22121)/n = (k\u22121)/(k\u00b7\u03b7<sub>p</sub>); H<sub>p</sub> = Z\u00b7R\u00b7T<sub>1</sub>\u00b7(n/(n\u22121))\u00b7[(P<sub>2</sub>/P<sub>1</sub>)<super>(n\u22121)/n</super>\u22121]; '
         '\u03b7<sub>p</sub> = 0.75; k \u2248 1.40 (3:1 H<sub>2</sub>/N<sub>2</sub>); Z \u2248 1.02\u20131.08 (H<sub>2</sub>-rich, do not assume below 1); 25\u201335 bar \u2192 150\u2013200 bar'],
        ['Synthesis converter', '3 adiabatic beds; per-bed equilibrium + 0.90\u20130.95 fractional approach',
         'Bed inlets 380\u2013430 \u00b0C; outlets capped 500\u2013530 \u00b0C; \u0394H = \u221246 kJ/mol NH<sub>3</sub> '
         'drives the adiabatic rise; outlet 14\u201318 mol% NH<sub>3</sub>; inlet (recycle) ~2 mol%'],
        ['Condenser / separator', 'PR-EOS flash (thermo library) with BIPs',
         'Chill to ~\u221220 \u00b0C (2-stage NH<sub>3</sub> refrigeration, COP \u2248 2.4); gas leaves with ~2\u20133% NH<sub>3</sub>; '
         'liquid product 99.5 wt%'],
        ['Circulator', 'Small booster compressor',
         '\u0394P 5\u201325 bar; \u03b7 \u2248 0.75'],
        ['Splitter (recycle/purge)', 'Pure mass balance',
         'Purge 5\u20138% of loop gas, holding inerts (CH<sub>4</sub>+Ar) at 10\u201315 mol%; recycle multiple \u2248 4\u20135\u00d7 makeup'],
    ],
    [0.16, 0.24, 0.60],
    caption='Table 4.2 — First-build modeling recipe. Sources: EFMA (2000); Flórez-Orrego and de Oliveira Junior (2017); Zečević and Bolf (2020); Johnson Matthey methanation data; Rice CENG403.',
    font_size=8.2)

P('Two structural notes on the table. First, the BAT loop arrangement adds makeup gas '
  '<i>after</i> ammonia condensation and takes purge after the separator and before makeup — '
  'getting this order right is the difference between matching published loop compositions and '
  'not. Second, the equilibrium-versus-kinetics question resolves cleanly: equilibrium with '
  'fractional approach reproduces plant outlets within 1\u20132 points of NH<sub>3</sub> with zero '
  'catalyst data, and the full Dyson\u2013Simon Temkin\u2013Pyzhev kinetics (constants in '
  'Fl\u00f3rez-Orrego; refits in the 2024 literature) become worth adding only when the product '
  'needs bed temperature profiles, catalyst loading, or part-load behavior. Keep kinetics out of '
  'the first build; design the converter API so they can drop in later.')

H2('4.3 The ammonia equilibrium constant, implementation-ready')
P('For \u00bdN<sub>2</sub> + (3/2)H<sub>2</sub> \u21cc NH<sub>3</sub>, the Gillespie\u2013Beattie '
  'correlation in partial-pressure (atm) terms:')
CODE([
    'log10 Kp = 2074.8/T \u2212 2.4943\u00b7log10 T \u2212 \u03b2\u00b7T + 1.856\u00d710<super>\u22127</super>\u00b7T<super>2</super> + I',
    'Kp = p_NH3 / ( p_N2^0.5 \u00b7 p_H2^1.5 )   [atm<super>\u22121</super>]',
])
P('with \u03b2 and I interpolated linearly in pressure between the rows below. Valid from '
  '325\u2013950 \u00b0C and 10\u2013300 atm — do not extrapolate beyond 300 bar. Beware the '
  'convention trap: if the reaction is written N<sub>2</sub> + 3H<sub>2</sub> \u21cc 2NH<sub>3</sub>, '
  'the equilibrium constant is the square of the half-reaction\u2019s.')

TBL(
    ['P (atm)', '\u03b2', 'I'],
    [
        ['10', '0', '1.993'],
        ['30', '3.4\u00d710<super>\u22125</super>', '2.021'],
        ['50', '1.256\u00d710<super>\u22124</super>', '2.090'],
        ['100', '1.256\u00d710<super>\u22124</super>', '2.113'],
        ['300', '1.256\u00d710<super>\u22124</super>', '2.206'],
    ],
    [0.34, 0.33, 0.33],
    caption='Table 4.3 — Pressure-dependent coefficients (Gillespie and Beattie, Phys. Rev. 36, 1930; table verified via El-Gharbawy 2021).',
    font_size=9, align_map={0: 'c', 1: 'c', 2: 'c'})

P('The implementation was re-verified during this research by solving the equilibrium composition '
  'for a stoichiometric feed at a grid of conditions; the resulting equilibrium NH<sub>3</sub> '
  'fractions reproduce the classic Larson\u2013Dodge/Vancini tables exactly, which is the '
  'strongest cheap correctness check available for this correlation.')

CHART('chart_equilibrium.png',
      'Figure 4.1 — Verified equilibrium NH<sub>3</sub> fraction versus temperature at four loop '
      'pressures (computed from the Table 4.3 correlation; spot-matches the classic tables). The '
      'annotated gap at 450 \u00b0C / 200 bar shows correction C1: the plan\u2019s 65% approach '
      'predicts 17.8 mol% where industry operates at 24.7\u201326.1 mol% (90\u201395% approach).',
      max_h=250)

H2('4.4 Convergence strategy for the synthesis loop')
P('Tear the recycle at the converter inlet (the standard choice) and solve the loop with a '
  'staged strategy rather than a single method:')
NUM(1, '<b>Iterations 1\u20133:</b> direct substitution with 0.5 damping — robust, gets into the '
       'correct basin while inert levels settle.')
NUM(2, '<b>Iterations 4\u201325:</b> bounded Wegstein acceleration per tear variable, with the '
       'acceleration factor clipped to [\u22125, 0] exactly as commercial simulators do; '
       'unbounded Wegstein is the classic cause of loop divergence.')
NUM(3, '<b>Stall fallback:</b> if not converged in ~25 iterations, switch to Broyden quasi-Newton '
       'on the 6\u20138 tear variables (component flows of N<sub>2</sub>, H<sub>2</sub>, '
       'NH<sub>3</sub>, CH<sub>4</sub>, Ar plus total flow and temperature). As a last resort, '
       'Luyben-style dynamic relaxation integrates the loop to steady state.')
NUM(4, '<b>Always:</b> initialize the tear stream near the answer — 13 mol% inerts, 2.5 mol% '
       'NH<sub>3</sub>, H<sub>2</sub>/N<sub>2</sub> = 2.7, 380 \u00b0C, loop pressure. A cold '
       'start from pure 3:1 syngas wastes iterations and invites the trivial no-reaction root.')
P('Expected cost: 10\u201320 loop evaluations cold; with warm-starting, a small what-if '
  'perturbation typically converges in a handful of evaluations — the entire basis for a '
  'conversation-speed recompute. Tolerance: 10<super>\u22124</super> to 10<super>\u22125</super> '
  'relative on tear molar flows.')

H2('4.5 Validation plan: what "correct" means, numerically')
P('Internal consistency is not validation. The engine earns credibility against four external '
  'anchors (Chapter 9), applied in escalating order: unit-level spot checks, then the once-through '
  'front-end train, then the loop, then whole-plant closure. The quantitative gates:')

TBL(
    ['Check', 'Target', 'Anchor'],
    [
        ['Whole-plant mass balance closure', 'below 10<super>\u22126</super> relative', 'internal'],
        ['Energy balance closure', 'within \u00b12%', 'internal'],
        ['Major stream compositions', 'within \u00b11\u20132 mol% absolute', 'EFMA ranges; TAMU stream tables'],
        ['Front-end temperatures and CH<sub>4</sub> slip', 'within \u00b115 \u00b0C / \u00b11% dry CH<sub>4</sub>', 'EFMA; Rice CENG403'],
        ['Converter outlet NH<sub>3</sub>', 'within 10% relative of 14\u201318 mol%', 'Fl\u00f3rez-Orrego; Shamiri'],
        ['Loop inerts and purge', 'inerts 10\u201315 mol%; purge 5\u20138%', 'EFMA; Fl\u00f3rez-Orrego'],
        ['Specific energy consumption', '28\u201331 GJ/t NH<sub>3</sub> (BAT band)', 'IFA/Frisse; IEA'],
    ],
    [0.40, 0.32, 0.28],
    caption='Table 4.4 — Validation gates. The golden stream tables become permanent regression tests.',
    font_size=8.8)

H2('4.6 Energy numbers worth hard-coding')
P('Best-available-technology SMR plants consume 28\u201329 GJ per tonne of NH<sub>3</sub> '
  '(Uhde\u2019s fleet: 6.6\u20137.2 Gcal/t); the 2008 IFA survey averaged 36.6 GJ/t across 93 '
  'plants and the IEA\u2019s global average sits near 41 GJ/t. These bands are what the v5 '
  'economics mode should reproduce before it earns opinions. For contrast, green ammonia needs '
  '10\u201312 MWh of electricity per tonne (electrolysis at ~53 kWh/kg H<sub>2</sub> plus air '
  'separation, compression and the loop), which at $30\u201370/MWh yields $300\u2013840/t of '
  'energy cost against $80\u2013270/t for natural gas at $3\u20138/MMBtu — a teaching-ready '
  'trade-off. Within the plant, the syngas compressor dominates the loop\u2019s power draw at '
  '61\u201375% (a 1000 MTPD plant totals ~13 MW optimal), and the reformer furnace is the '
  'largest fuel consumer (~58 MW at 1000 MTPD in the Rice design); HP steam at ~100 bar raised '
  'across the convection bank, secondary waste-heat boiler and synloop boilers drives the '
  'compressor turbines. Modeling even a simplified steam header makes the energy narrative '
  'honest.')


# ── Chapter 5: The Interactivity Frontier ───────────────────────────────────
H1('5. The Interactivity Frontier')

P('The plan\u2019s roadmap already gestures at an "extremely interactive" product; this chapter '
  'maps how far that can actually go in 2025\u20132026, what each step costs a solo developer, '
  'and which patterns make the difference between a demo that impresses for a minute and one '
  'that people refuse to close. Three frontiers are explored in depth — live voice, 3D space, '
  'and gamified operations — followed by the design science that should govern all of them.')

H2('5.1 The interactivity ladder')
P('Fifteen concrete features, ranked by wow-per-unit-effort. Effort figures assume a competent '
  'solo developer already holding a working engine; they exclude the engine itself.')

TBL(
    ['#', 'Feature', 'Effort', 'Depends on', 'Risk'],
    [
        ['1', '3D stream-flow shader — UV-scroll on pipe meshes; speed \u221d mass flow, color \u221d temperature', '2\u20133 d', 'Three.js tube geometry + engine rates', 'Low'],
        ['2', 'Live PFD — React Flow with marching-dash streams and live T/P/flow labels', '2\u20134 d', 'React Flow (MIT); memoized nodes', 'Low'],
        ['3', 'Sentence-chunked streaming narration — TTS starts on the first sentence', '1\u20133 d', 'Streaming LLM + streaming TTS', 'Low'],
        ['4', 'Interruptible narration — 60\u201390 s beats, pause/resume/discard on any input', '2\u20135 d', 'Beat timeline; browser audio', 'Low\u2013Med'],
        ['5', 'Exploded-view slider + click-to-inspect unit cards', '3\u20135 d', 'R3F; tag registry', 'Low'],
        ['6', 'Push-to-talk what-if — STT \u2192 LLM tool-call \u2192 recompute \u2192 spoken answer', '3\u20137 d', 'STT; tool-calling LLM', 'Medium'],
        ['7', 'Fault-injection operator mode (steady-state) — fouling, deactivation, efficiency, dP', '1\u20132 wk', 'Fault whitelist; alarms; KPI deltas', 'Medium'],
        ['8', 'P&ID \u2194 3D bi-directional sync — no web precedent found', '1\u20132 wk', 'Shared tag registry; camera tweens', 'Medium'],
        ['9', 'Scenario challenges + scoring — briefing \u2192 ops \u2192 score \u2192 debrief', '1\u20132 wk', 'Feature 7; scoring engine', 'Medium'],
        ['10', 'First-person walkthrough with proximity narration', '1\u20132 wk', 'R3F controls; LOD', 'Medium'],
        ['11', 'Full-duplex "talk to the plant" — Realtime API with barge-in', '1\u20133 wk', 'OpenAI Realtime or LiveKit/Pipecat', 'High'],
        ['12', 'Instructor station — set initial conditions, inject faults remotely', '2\u20134 wk', 'Features 7 + 9', 'Medium'],
        ['13', 'Quasi-dynamic plant clock — steady solve per game tick + inventory integrators', '1\u20133 wk', 'Solve time under 0.5 s; holdup data', 'High'],
        ['14', 'AI-authored fault briefs — LLM writes scenario + rubric, engine validates', '3\u20137 d', 'Fault whitelist guardrails', 'Medium'],
        ['15', 'Leaderboards + shareable scenario cards', '3\u20135 d', 'Feature 9; light backend', 'Low'],
    ],
    [0.05, 0.47, 0.10, 0.24, 0.14],
    caption='Table 5.1 — The interactivity ladder. Rungs 1\u20136 form the "alive plant" tier; 7\u20139 the operator-training tier; 11+ the headline-demo tier.',
    font_size=8.2, align_map={0: 'c', 2: 'c', 4: 'c'})

CHART('chart_ladder.png',
      'Figure 5.1 — The ladder in the effort-impact plane. Color encodes roadmap tier: blue = alive '
      'plant (stage S4), teal = operator mode (S5), red = headline-demo tier. The upper-left '
      'cluster is the highest-return work available to this product.',
      max_h=255)

H2('5.2 Frontier A — live conversational voice')
P('The perceived-quality budget for voice is brutally concrete. Nielsen\u2019s thresholds still '
  'govern: 0.1 s feels instantaneous, 1 s is the limit of flow, 10 s is the attention limit. '
  'Voice specifically: humans take turns with a 200\u2013300 ms gap; first audio under 600 ms '
  'feels natural and under 400 ms feels excellent — while the median production voice agent '
  'today still answers in 1.4\u20131.7 s. The good news is that the gap is closable with '
  'engineering, not research.')

TBL(
    ['Interaction', 'Budget', 'Technique'],
    [
        ['Slider drag / camera move', 'under 0.1 s', 'Client-side interpolation; precomputed solution surfaces'],
        ['What-if recompute + visual update', '0.5\u20132 s', 'Warm-started solve; optimistic UI — animate flows toward new rates immediately'],
        ['Narration start after an event', 'under 0.6 s', 'Sentence-chunked streaming TTS (first ~24-token segment)'],
        ['Voice Q&A turn', 'under 1 s (ideally 0.6)', 'Realtime API, or Deepgram STT + LLM + Flash-class TTS pipeline'],
        ['Fault scenario tick', '0.5\u20132 s / step', 'Quasi-steady solver stepping'],
        ['Anything slower than 1 s', 'visible feedback', 'Pulsing pipes, status chip, or a spoken filler ("let me re-solve the loop")'],
    ],
    [0.32, 0.18, 0.50],
    caption='Table 5.2 — Latency budget for the product. Every row has a known technique; none requires research.',
    font_size=8.8)

CHART('chart_latency.png',
      'Figure 5.2 — Achievable voice latencies by architecture, against the ~0.6 s natural-feel '
      'threshold. Sentence-chunked turn-taking already lands inside the band; full-duplex '
      'speech-to-speech closes most of the rest.',
      max_h=235)

P('<b>Two architectures, staged.</b> The turn-based pipeline (STT \u2192 LLM \u2192 TTS) naively '
  'costs 1.3\u20132 s, but sentence-chunked streaming — start TTS on the first sentence while the '
  'LLM keeps generating — reaches 0.42\u20130.52 s and needs only commodity APIs. That is the '
  'right v2 path. Full-duplex speech-to-speech (OpenAI Realtime over WebRTC, with function '
  'calling so the model can invoke the engine mid-conversation) delivers 0.5\u20130.8 s with true '
  'barge-in at roughly $0.04/min of speech after the 2025 price cuts — the right v3+ "live call" '
  'mode. Self-hosted alternatives (LiveKit Agents, Pipecat) exist if API cost or data residency '
  'demands them. The browser\u2019s built-in Web Speech API is the free fallback tier — good '
  'enough for a mute/read mode and always-available on desktop Chrome and Safari, but unreliable '
  'as the flagship (no custom vocabulary: it will mangle "Wegstein" and "Haber").')

P('<b>Interruptible narration is a design pattern, not a feature.</b> Museum audio-guide craft '
  'suggests the shape: segment the walkthrough into 60\u201390 s stops (110\u2013170 spoken '
  'words), each tied to a visual event — a unit assembling, a stream lighting up. Any click, key '
  'press or speech pauses audio; if the user resumes quickly, play on; if they keep talking, '
  'discard the pending beats and answer. This makes narration seekable like a timeline, which '
  'also solves the "replay that part about the purge" request every teacher will make. Be warned '
  'that interruption handling in production voice AI is still genuinely hard — barge-in triggers '
  'on filler words and echo — so the pause gesture should be explicit (tap or spacebar) in v2, '
  'with true open-microphone barge-in deferred to the Realtime-API stage.')

H2('5.3 Frontier B — the 3D spatial plant')
P('The performance currency of the web is draw calls, not triangles: scenes under ~100 draw '
  'calls run at 60 fps on most laptops, above ~500 even strong machines struggle. An ammonia '
  'plant — a dozen equipment groups plus a pipe rack — fits comfortably in 50\u2013300 draw '
  'calls and 100\u2013500k triangles once geometry is merged and instanced, which means 60 fps '
  'on the integrated GPUs students actually own. Three.js with React Three Fiber is the clear '
  'stack choice: it loads in 2\u20136 s where Unity WebGL takes 8\u201330 s, runs at 95\u201399% '
  'of raw WebGL performance, and — decisively for this product — lives inside the same React '
  'state tree as the engine results. Unity would fight the stack for no gain.')

B('<b>Flow animation:</b> scroll a stripe texture along each pipe\u2019s UVs (speed proportional '
  'to the solved mass flow, color to temperature) — roughly one draw call per material for '
  'every stream in the plant. Reserve GPU particles for two or three hero streams (feed gas, '
  'liquid ammonia product); real fluid solvers are overkill.')
B('<b>The 2D twin:</b> a live PFD in React Flow (MIT-licensed, nodes are React components, so '
  'live-updating stream labels are trivial) with marching-dash animation on stream edges. '
  'Perf hygiene matters — memoize nodes or re-renders will crawl — but the pattern is proven '
  'at 300+ nodes, and Siemens ships a React Flow modeler for process diagrams as validation '
  'of the approach.')
B('<b>The differentiator:</b> bi-directional P&ID\u20143D sync. Click a vessel in 3D, it '
  'highlights on the PFD with a camera fly-to; click a stream on the PFD, the pipe glows in '
  '3D. Research found this only in enterprise plant-design suites (AVEVA), never on the web. '
  'Implementation is unglamorous plumbing — a shared equipment-tag registry mapping '
  'tag \u2192 PFD node id \u2192 3D object id \u2192 engine unit id, plus selection events and '
  'camera tweens — which is exactly why it is defensible.')
B('<b>Day-one restraint:</b> the MVP needs block-out geometry (procedural cylinders, boxes and '
  'tube runs) with correct spatial arrangement, not photorealism. Exploded-view sliders and '
  'click-to-inspect cards (rung 5) deliver more perceived quality per hour than texture work '
  'ever will.')

H2('5.4 Frontier C — gamified operations')
P('The OTS industry\u2019s formula is dynamic model + emulated controls + instructor station + '
  'scoring, at $800k\u2013$3M a seat. A steady-state engine cannot honestly replicate all of '
  'that — and pretending otherwise would be the fastest way to lose an engineer\u2019s respect. '
  'The honest version is "sensitivity analysis dramatized," and it is genuinely pedagogical:')

TBL(
    ['Fault (steady-state-honest)', 'Parameter delta', 'What the student sees'],
    [
        ['Condenser fouling', 'lower U / larger approach', 'Colder separator temperature needed; NH<sub>3</sub> losses up; refrigeration duty up'],
        ['Catalyst deactivation', 'bed approach 0.95 \u2192 0.85', 'Outlet NH<sub>3</sub> falls; recycle and purge flows rise; production drops'],
        ['Compressor degradation', '\u03b7<sub>p</sub> 0.75 \u2192 0.68', 'Power draw climbs; energy KPI degrades; steam balance tightens'],
        ['Feed drift', 'H<sub>2</sub>/N<sub>2</sub> off 3:1', 'Conversion collapse the student must diagnose and correct'],
        ['Inert buildup', 'purge partially blocked', 'Loop pressure and inerts creep; the purge story becomes physical'],
        ['Cooling-water degradation', 'CW temperature +10 \u00b0C', 'Condensation worsens; loop efficiency falls'],
        ['Pressure-drop fault', 'dP multiplier \u00d71.5', 'Circulator work up; a lesson in hydraulic design margin'],
    ],
    [0.24, 0.24, 0.52],
    caption='Table 5.3 — Steady-state fault taxonomy: every fault is a parameter delta \u2192 re-solve \u2192 KPI deltas and alarms. This is the v3 operator mode.',
    font_size=8.6)

P('What steady state cannot do honestly: trips, startup and shutdown sequences, compressor '
  'surge, relief events, oscillations, and anything scored on response time. The bridge is '
  '<b>quasi-steady stepping</b> — re-solve the plant every 0.5\u20132 s of "plant time," '
  'interpolate between solutions, and treat drum and loop inventories as simple integrators '
  'so levels drift as faults develop. Many educational simulators do exactly this; the '
  'requirement is honest labeling ("quasi-steady") and a solver fast enough for the tick, '
  'which the warm-started engine satisfies. Scoring, borrowed from OTS practice where the '
  'debrief is where learning happens: keep-operating-band, time-to-diagnose (once the clock '
  'exists), final production and energy, alarms acknowledged — wrapped in a '
  'briefing \u2192 operations \u2192 score \u2192 debrief loop. Evidence from the serious-games '
  'literature (2023\u20132025 systematic reviews) supports the mechanics: points, challenges '
  'and scenarios reliably lift engagement and help retention, with the strongest learning '
  'gains coming from scenario-plus-debrief structure rather than decoration. GSE\u2019s own '
  '2026 move — AI authoring fault scenarios from natural language — is the industrial '
  'blessing of exactly this feature (rung 14).')

H2('5.5 The design science underneath')
P('PhET\u2019s Colorado sims, the most studied interactive learning artifacts in existence, '
  'distill to five principles that map onto this product almost verbatim: direct manipulation '
  'with immediate feedback (grab the parameter, see the plant answer); make the invisible '
  'visible (flow speed as animation speed, temperature as color); real-world connections '
  '(this is a real plant with real published numbers); minimal text (the voice carries the '
  'explanation); constrained controls that scaffold exploration (sliders bounded by physical '
  'ranges, not free text fields). The explorable-explanations tradition adds two more: '
  'one-step interactions — every drag should produce a visible consequence — and persistent '
  'context: never collapse the old state when showing the new, which for this product means '
  'the what-if answer must show before/after side by side, keeping the prior plant visible '
  'for comparison. These are cheap rules to follow at design time and expensive to retrofit; '
  'they belong in the first wireframe, not the second release.')

# ── Chapter 6: Recommended Technology Stack ─────────────────────────────────
H1('6. Recommended Technology Stack')

P('The plan\u2019s candidate list (Cantera, CoolProp, Piper, OpenAI, ElevenLabs, Azure) was '
  'verified against current pricing, licensing and capability. Verdicts below are for this '
  'product specifically — a teaching app with a deterministic engine, voice narration and a '
  'student audience — not general rankings.')

H2('6.1 The stack, layer by layer')
TBL(
    ['Layer', 'Primary pick', 'Budget alternative', 'Why'],
    [
        ['Engine core', 'Custom unit ops + hand-coded K<sub>p</sub> correlations', 'Same (there is no shortcut)', 'Determinism, narrative control, warm-start latency'],
        ['Loop VLE + enthalpies', '<i>thermo</i> (MIT): PR-EOS with BIPs, flashes', 'CoolProp pure-fluids + K-value condenser shortcut', 'Only mainstream library that flashes NH<sub>3</sub> mixtures at loop conditions'],
        ['Pure-fluid properties + steam', 'CoolProp (MIT; NH<sub>3</sub> EOS to 725 K / 1000 MPa; IF97 steam)', '<i>iapws</i> for steam only', 'Bulletproof pure-fluid layer; never use it for the mixture flash'],
        ['Equilibrium cross-check', 'Cantera (BSD): Gibbs minimization, offline', 'Skip', 'Independent second opinion on reformer/shift equilibrium'],
        ['Intake + what-if LLM', 'OpenAI structured outputs (strict schema) via Instructor + Pydantic', 'Any provider through the same Instructor layer', '100% schema adherence; reliability lives in the Pydantic envelope, not the vendor'],
        ['Narration TTS', 'OpenAI gpt-4o-mini-tts (~$0.015/min; voice-instructions persona)', 'Kokoro-82M self-host (Apache 2.0) or Azure free tier', 'Persona control ("calm plant instructor") is a pedagogical feature'],
        ['Conversational TTS', 'ElevenLabs Flash v2.5 (75 ms TTFB, $50/1M chars)', 'Azure Speech free tier (500k neural chars/month)', 'Latency class for the Q&A loop'],
        ['STT', 'Deepgram Whisper-class (~150 ms)', 'Browser Web Speech API', 'Accuracy-speed balance; word boosting for jargon'],
        ['Full-duplex voice (v3+)', 'OpenAI Realtime API over WebRTC (~$0.04/min)', 'LiveKit Agents or Pipecat self-host', 'Barge-in conversations that call the engine mid-turn'],
        ['3D render', 'Three.js + React Three Fiber', 'Babylon.js', '2\u20136 s loads; lives in React state; 60 fps within draw-call budget'],
        ['2D PFD', 'React Flow (MIT)', 'AntV X6', 'Nodes are React components \u2192 live labels are trivial'],
        ['Validation oracle', 'DWSIM (offline, scripted via Python)', 'None', 'Second opinion on the whole flowsheet; GPL is fine offline'],
    ],
    [0.17, 0.29, 0.22, 0.32],
    caption='Table 6.1 — Recommended stack. All primary picks are free or metered-in-cents for this scale.',
    font_size=8.2)

H2('6.2 TTS economics, verified')
P('TTS pricing moved decisively in favor of small builders: Amazon gutted its perpetual free '
  'tier in July 2025 (replaced by one-time $200 credits — skip Polly), while Azure\u2019s '
  '500k free neural characters per month remains ongoing, Google gives 4M standard characters '
  'free monthly, and OpenAI\u2019s mini TTS model prices at roughly $0.015 per minute with a '
  'voice-instructions channel that can lock an instructor persona. At the top end, ElevenLabs '
  'remains the quality ceiling at $50\u2013100 per million characters with a 75 ms '
  'time-to-first-byte Flash tier built for agents.')

CHART('chart_tts_price.png',
      'Figure 6.1 — TTS list prices per million characters (2025\u20132026). Green bars carry a '
      'genuine free tier; the vertical spread is 100\u00d7, yet a semester of narration costs '
      'pennies even at the top.',
      max_h=250)

TBL(
    ['Scenario', 'Compute', 'Cost'],
    [
        ['100 pre-generated walkthroughs \u00d7 3 min', 'OpenAI mini-TTS', '\u2248 $4.50 \u2014 or $0 within Azure\u2019s 500k free monthly chars'],
        ['500 conversational answers \u00d7 30 s', 'ElevenLabs Flash', '\u2248 $12.50 \u2014 or $0 (Kokoro self-host / Azure free)'],
        ['A "live call" session, 20 min', 'OpenAI Realtime', '\u2248 $0.80 \u2014 plus ~$0.20/h idle keep-alive'],
    ],
    [0.40, 0.24, 0.36],
    caption='Table 6.2 — TTS cost sanity check. Voice quality and latency are the real decisions; money is not.',
    font_size=8.8)

H2('6.3 The LLM integration pattern, specified')
P('The reliability stack has four stages, and the interesting truth is that the vendor '
  'provides only the first: schema guarantees are format-level, not value-level — a model '
  'can return 900 bar in perfectly valid JSON. Numeric hallucination is a documented LLM '
  'failure class with engineering-specific propagation risks, so the architecture must make '
  'bad values die before they reach the engine.')

CODE([
    '1. LLM call with strict JSON schema (enums for units, additionalProperties: false)',
    '2. Pydantic validation with hard physical ranges:',
    '   loop_pressure: 80\u2013250 bar   S/C ratio: 2\u20134   bed temps: 350\u2013530 \u00b0C',
    '   converter approach: 0.85\u20130.97   purge fraction: 0.02\u20130.15',
    '3. On rejection \u2192 one clarifying retry \u2192 then defaults + visible flag',
    '4. Engine computes everything numeric; the LLM only narrates engine output,',
    '   with numbers injected server-side into its templates',
])

P('Instructor (MIT) provides the retry plumbing provider-agnostically, so OpenAI, Anthropic '
  'or a local model can sit behind the same interface — worth building that abstraction on '
  'day one not for ideology but because pricing and capability will keep moving. The '
  'fallback ladder for open-ended questions ("why does the purge stream exist?") is '
  'retrieval over a small corpus of grounded material — the EFMA booklet, Ullmann\u2019s '
  'ammonia chapter, the sources in Chapter 9 — with the engine\u2019s live numbers '
  'interpolated into the answer. Every physical claim the product makes should be traceable '
  'either to a tool call or to a retrieved passage; that traceability is the product\u2019s '
  'integrity, and it is also the demo you show skeptics.')

H2('6.4 Cost model at three scales')
TBL(
    ['Scale', 'Assumptions', 'Monthly cost, paid stack', 'Free-tier path'],
    [
        ['Single user (you)', '40 sessions; 10 what-ifs each', '\u2248 $3\u20136', '\u2248 $0'],
        ['One classroom (30 students)', '3 sessions/student/month; voice on', '\u2248 $25\u201360', '\u2248 $0\u20135'],
        ['Public launch (1,000 users/mo)', '2 sessions/user; 20% voice', '$250\u2013900', '$30\u201380 (Kokoro + Azure free + rate limits)'],
    ],
    [0.26, 0.28, 0.24, 0.22],
    caption='Table 6.3 — Operating cost at three scales, dominated by LLM tokens and realtime voice minutes. The free-tier path exists at every scale.',
    font_size=8.8)

P('The strategic reading of this table: cost never blocks the mission. Even the paid stack at '
  'public-launch scale is a rounding error against any institutional budget, and the free-tier '
  'path (self-hosted Kokoro, Azure\u2019s perpetual free characters, Web Speech fallback, '
  'aggressive caching of narration for repeated parameter sets) keeps the product sustainable '
  'at zero. The costs that actually matter are the ones money cannot fix: solver latency, '
  'voice naturalness on jargon, and the honesty of the what-if loop.')


# ── Chapter 7: Risk Register ────────────────────────────────────────────────
H1('7. Risk Register')

P('Risks are ranked by expected damage to the product\u2019s core promise: an engineer-checkable '
  'plant behind an extremely interactive face. Impact (I) and likelihood (L) are scored '
  'high/medium/low; every risk carries a mitigation that is already implied by earlier chapters.')

TBL(
    ['ID', 'Risk', 'I', 'L', 'Mitigation'],
    [
        ['R1', 'Recycle convergence stalls or diverges on what-if edge cases, breaking the "instant recompute" feel', 'H', 'M',
         'Bounded Wegstein + Broyden fallback (4.4); clamp what-if parameter deltas; on failure, fall back to last converged state with an honest message'],
        ['R2', 'LLM emits schema-valid but physically absurd parameters', 'H', 'M',
         'Pydantic physical-range envelope + one clarifying retry + defaults with visible flag (6.3)'],
        ['R3', 'Narration drifts from the engine numbers under iteration pressure', 'H', 'L',
         'Templates inject numbers server-side; LLM frames but never computes; regression test compares spoken text to engine output'],
        ['R4', 'PR-EOS condenser split deviates from plant data beyond teaching tolerance', 'M', 'L',
         'Validate flash against Fl\u00f3rez-Orrego loop tables; fall back to K-value correlation; cite Herrmann 2020 as reference target'],
        ['R5', 'Free-tier policy changes (Polly precedent, July 2025) strand the voice budget', 'M', 'M',
         'Provider abstraction layer; Kokoro self-host as the permanent floor; cache narration audio by parameter hash'],
        ['R6', 'Voice latency misses the 0.6 s bar and the product feels sluggish', 'H', 'M',
         'Sentence-chunked streaming as the default; precompute first-sentence audio for canonical questions; optimistic visuals while solving'],
        ['R7', 'Scope creep beyond ammonia (CO2 plants, methanol, "just one more unit op")', 'H', 'H',
         'The roadmap\u2019s stage gates; new plants are a v6+ question, and the architecture already isolates unit ops for that day'],
        ['R8', '3D scene drops frames on school laptops', 'M', 'M',
         'Draw-call budget (\u2264300) enforced in code review; instancing/merging; LOD; measure on integrated GPUs, not the dev machine'],
        ['R9', 'DWSIM 10\u2019s free AI assistant neutralizes the "why build this?" story', 'M', 'M',
         'Differentiate on pedagogy, voice, ammonia depth and the student experience; keep the one-screen "why not DWSIM" answer in-product'],
        ['R10', 'MaximaLabs or an incumbent ships a free edu tier first', 'M', 'M',
         'Speed: the niche is small enough to be unattractive to them for a while; the ammonia-specific narrative is hard to retrofit'],
        ['R11', 'Solo-maintainer burnout; the 27-week plan slips', 'H', 'H',
         'Stage gates sized for sustainable part-time cadence; the MVP demo lands at week 13 precisely to pay motivation forward'],
        ['R12', 'API cost blowout if a demo goes viral', 'M', 'M',
         'Free-tier-first stack (6.4); per-session rate limits; narration caching; realtime voice behind an opt-in toggle'],
        ['R13', 'ASR mangles process jargon ("Wegstein", "Haber", "Temkin")', 'M', 'M',
         'Word boosting / custom vocabulary on Deepgram; push-to-talk UX; show the recognized text for correction before solving'],
        ['R14', 'Pressure to chase green-ammonia scope before the SMR core is validated', 'M', 'L',
         'Electrolysis front-end is a parameter set + one new unit in v5+; do not touch before S2 validation gates pass'],
        ['R15', 'Teaching content carries an unverified number into the world', 'M', 'M',
         'Every number in narration traces to Chapter 9 sources or engine output; rationale mode cites passages, not memory'],
    ],
    [0.05, 0.40, 0.05, 0.05, 0.45],
    caption='Table 7.1 — Risk register, ranked by expected damage. R7 and R11 are the two high-likelihood items, and both are roadmap discipline problems rather than technical ones.',
    font_size=8.0, align_map={0: 'c', 2: 'c', 3: 'c'})

P('Read as a set, the register says something useful: the technical risks are all mitigated by '
  'specifications already in this dossier, and the two risks most likely to kill the project '
  'are behavioral — scope creep and burnout. The roadmap in the next chapter is designed '
  'around exactly those two.')


# ── Chapter 8: Roadmap v2 ───────────────────────────────────────────────────
H1('8. Roadmap v2: Stages, Effort and the Critical Path')

P('The original five-stage roadmap (MVP \u2192 what-if \u2192 faults \u2192 exports \u2192 '
  'economics) keeps its shape but gets three changes: validation becomes a stage with gates '
  'instead of a sentence; the MVP\u2019s 3D render is re-scoped to block-out geometry so the '
  'demo lands at week 13 instead of week 20; and every stage carries an effort estimate in '
  'working weeks for a solo developer working part-time (roughly halve them full-time).')

H2('8.1 The stages')
TBL(
    ['Stage', 'Weeks', 'Deliverables', 'Exit gate'],
    [
        ['S0 — Foundations', '0\u20132',
         'Stream object (Table 4.1); thermo core (<i>thermo</i> + CoolProp); splitter/mixer; plumbing tests; regression harness skeleton',
         'Mass balance closes to 10<super>\u22126</super> on synthetic networks'],
        ['S1 — Front-end train', '2\u20135',
         'Desulfurizer, both reformers (two-zone secondary), HTS/LTS, CO<sub>2</sub> removal, methanator, compressor',
         'Front-end matches EFMA/Rice ranges (Table 4.4 rows 3\u20134)'],
        ['S2 — Synthesis loop + validation', '5\u20139',
         'Converter (3 beds, 0.90\u20130.95 approach), PR-EOS condenser, circulator, splitter; tear solver (4.4); DWSIM cross-check',
         'All Table 4.4 gates pass; golden stream tables committed as tests'],
        ['S3 — MVP shell', '9\u201313',
         'Intake LLM + Pydantic envelope; narration script from real results; TTS; block-out 3D scene; guided voice walkthrough',
         'A chemical engineer builds a plant from a spec and hears true numbers'],
        ['S4 — v2 alive plant', '13\u201317',
         'What-if tool-calling loop with warm start; live PFD (rung 2); stream-flow shader (rung 1); streaming + interruptible narration (rungs 3\u20134); push-to-talk (rung 6)',
         'Ten canonical what-ifs answered in under 2 s with recomputed numbers'],
        ['S5 — v3 operator mode', '17\u201322',
         'Fault whitelist + alarms + KPI deltas (rung 7); scenario scoring + debrief (rung 9); AI-authored briefs (rung 14)',
         'A full fault scenario plays start to debrief'],
        ['S6 — v4 exports', '22\u201324',
         'Mass/energy balance tables; PFD image export; session report',
         'Exported tables pass the same validation gates as the engine'],
        ['S7 — v5 economics', '24\u201327',
         'Energy integration numbers, SMR vs green-ammonia trade-offs, design comparison mode',
         'BAT band 28\u201331 GJ/t reproduced; comparison mode demos cleanly'],
    ],
    [0.20, 0.08, 0.44, 0.28],
    caption='Table 8.1 — Roadmap v2. Headline-demo tiers beyond S5 (full-duplex talk, instructor station, quasi-dynamic clock) are deliberately unestimated until S5 ships.',
    font_size=8.2)

CHART('chart_roadmap.png',
      'Figure 8.1 — Roadmap v2 on the calendar. The MVP demo at week 13 is the motivation '
      'engine for everything after it; validation (S2) is the credibility engine.',
      max_h=240)

H2('8.2 What changes from the original plan, and why')
B('<b>Validation is stage S2, not an afterthought.</b> The original plan\u2019s build order ends '
  'with "validate against a published mass/energy balance" — correct instinct, wrong position. '
  'The gates in Table 4.4 must pass before the MVP shell consumes engine output, or the '
  'narration will memorize wrong numbers and the 3D scene will animate wrong flows.')
B('<b>The MVP keeps 3D but drops polish.</b> The original "3D render" in MVP is the right '
  'demo instinct; block-out geometry with the flow shader (2\u20133 days) delivers 80% of the '
  'perceived magic. Photoreal equipment, first-person walking and P&ID sync move to S4/S5 '
  'where they compound with the what-if loop instead of delaying it.')
B('<b>Exports moved ahead of economics.</b> v4-before-v5, unchanged from the plan, and '
  'reaffirmed: a student\u2019s assignable artifact (the mass-balance table) spreads the '
  'product through the channel that matters — coursework — before opinions about money '
  'exist.')
B('<b>The headline-demo tier is unscheduled on purpose.</b> Full-duplex conversation, '
  'instructor station and the quasi-dynamic clock are the v3+ frontier; estimating them now '
  'would be theater. They appear in Table 5.1 with dependencies so the architecture '
  'accommodates them cheaply, but the calendar stops at S7.')

H2('8.3 The critical path: protect the what-if loop')
P('The original plan contains its own most important sentence — that the gap between MVP and '
  'v5 is whether the what-if loop is real or fake — and every finding in this research '
  'sharpens it. "Real" has a precise, testable definition: the user\u2019s utterance becomes '
  'a parameter delta; the delta passes the physical envelope; the engine recomputes from the '
  'warm-started state; the narration reports the before/after diff from engine output. Any '
  'path where the LLM describes a consequence without a tool call having produced it is the '
  'failure mode. Three defenses keep that path intact:')

NUM(1, '<b>A truthfulness test in every release gate.</b> Ten canonical what-ifs with '
       'known answers (pressure 250 bar; purge halved; LT-shift approach degraded; and so '
       'on) run against every build; a wrong trend or a fabricated number fails the release.')
NUM(2, '<b>Optimistic UI that never lies.</b> Flows may animate speculatively toward the new '
       'state, but numbers displayed as truth come only from converged solves — label the '
       'in-between honestly ("solving\u2026").')
NUM(3, '<b>Provenance on every claim.</b> Each spoken sentence about the plant is generated '
       'from engine output or a retrieved, citable passage — never free generation. The '
       'diagnosis mode inherits this rule, which is what makes it a teacher rather than a '
       'chatbot.')

CAL('<b>The one-sentence version:</b> ship a plant whose numbers are checkable, wrap it in '
    'interactions that answer in under a second, and never let the language model near the '
    'arithmetic. Everything else in this dossier is detail.')


# ── Chapter 9: Validation Source Library ────────────────────────────────────
H1('9. Validation Source Library')

P('The ranked anchors for engine validation, followed by the key web sources behind the '
  'stack and landscape chapters. For each: what it provides and how to use it. The '
  'recommended practice is to transcribe the numeric tables below into a versioned golden '
  'stream-table file on day one; the regression harness then compares every build against '
  'it automatically.')

H2('9.1 Engineering anchors, ranked')
TBL(
    ['#', 'Source', 'Provides', 'Access'],
    [
        ['1', 'EFMA / Fertilizers Europe, "Production of Ammonia" BAT Booklet No. 1 (2000)',
         'Typical T/P/composition ranges for every section of a conventional SMR plant — the flowsheet-level sanity check',
         'Free PDF (productstewardship.eu)'],
        ['2', 'Fl\u00f3rez-Orrego and de Oliveira Junior, Energy 137 (2017) 234\u2013250 (free ECOS 2016 version)',
         'The most complete public synthesis-loop dataset: 1000 MTPD unit, bed temperatures, per-bed conversions, recycle composition, power split, COP, kinetic constants',
         'Free PDF (EPFL infoscience)'],
        ['3', 'Mahmoud, M.S. thesis, Texas A&M (2024)',
         'Aspen Plus model of a conventional SMR ammonia plant with full stream-by-stream mass-balance tables — the closest thing to a complete citable stream table',
         'Thesis repository (oaktrust.library.tamu.edu)'],
        ['4', 'Rice University CENG403 ammonia design projects (1997)',
         'Three coordinated 1000\u20131016 MTPD designs with ASPEN numbers: reformer (800 \u00b0C, 35.3 bar, S/C 3), secondary outlet flows, loop (100 bar, 7.25% purge, 19% per pass)',
         'Free HTML (owlnet.rice.edu)'],
        ['5', 'Cheema and Krewer, RSC Advances 8 (2018) 34926',
         'Open-access rigorous Dyson\u2013Simon converter model with all equations and constants; 200 bar / 673\u2013773 K bed design; the kinetics upgrade reference',
         'Open access (rsc.org / pure.mpg.de)'],
        ['6', 'Ze\u010devi\u0107 and Bolf, Processes 8(4):408 (2020)',
         'Reformer equilibrium constants (K<sub>SR1</sub>, K<sub>WGS</sub>) and approach-to-equilibrium benchmarks, validated on industrial data',
         'Free PDF (mdpi.com)'],
        ['7', 'Gillespie and Beattie, Phys. Rev. 36 (1930) 743; tables via El-Gharbawy 2021',
         'The ammonia equilibrium correlation and its pressure-dependent coefficients (Table 4.3), verified in this research',
         'Journal; free via Egypt. J. Chem.'],
        ['8', 'Supporting set: Shamiri et al. (2021) plant-validated loop; IFA/Frisse (2004) Uhde plant data; IEA Ammonia Technology Roadmap (2021) energy statistics; Herrmann et al., Fluid Phase Equilibria (2020) loop-binary reference EOS',
         'Cross-checks, energy anchors and the thermodynamic gold standard for the condenser',
         'Mixed free/paywalled'],
    ],
    [0.05, 0.33, 0.42, 0.20],
    caption='Table 9.1 — Validation library. Sources 1\u20134 close the mass balance; 5\u20137 close the converter; 8 closes the condenser and the energy story.',
    font_size=8.0)

H2('9.2 How to use the library')
P('Sequence matters. Use source 1 first to bound every section during S0\u2013S1 (it exists '
  'precisely to describe BAT plants). Use source 4 (free, plain HTML, coarse) as the first '
  'whole-train check in S1, then source 2 as the deep loop reference in S2 — its tables '
  'cover exactly the variables the tear solver manipulates. Transcribe source 3\u2019s '
  'stream tables into the golden file when access is secured (it sits behind a CDN block; a '
  'library request resolves it). Source 5 is dormant until the kinetics upgrade, source 6 '
  'guards the reformer, source 7 ships inside the engine, and source 8\u2019s reference EOS '
  'defines what "accurate" means for the condenser flash if PR-EOS results are ever '
  'disputed. This ordering turns a reading list into a test suite.')

H2('9.3 Key web sources for the stack and landscape chapters')
P('For provenance, the load-bearing web sources behind Chapters 3, 5 and 6: DWSIM (dwsim.org) '
  'for engine capabilities, licensing and the DWSIM 10 AI assistant; MaximaLabs '
  '(maximalabs.io) for browser-simulator pricing tiers; AspenTech\u2019s academic program and '
  'student-promo pages for the cost wall; LearnChemE (learncheme.com) and Annenberg\u2019s '
  'Haber interactive for the educational layer; GSE Solutions (gses.com) for OTS practice, '
  'installed base and the Nuclearn AI collaboration; OpenAI\u2019s realtime, structured-outputs '
  'and TTS pricing pages; ElevenLabs, Azure Speech and Deepgram pricing pages for the voice '
  'stack; the React Flow documentation (reactflow.dev) for PFD performance practice; and the '
  'React Three Fiber guides for the 3D scaling rules. These were all verified live in August '
  '2026; the fast-moving prices should be re-checked before any procurement decision.')


# ═════════════════════════════════════════════════════════════════════════════
# BUILD
# ═════════════════════════════════════════════════════════════════════════════
doc = TocDocTemplate(
    OUT_BODY, pagesize=A4,
    leftMargin=MARGIN, rightMargin=MARGIN,
    topMargin=MARGIN, bottomMargin=MARGIN,
    title=DOC_TITLE, author='Z.ai', creator='Z.ai',
    subject='Pre-build research, plan stress test, interactivity roadmap and technology stack for an ammonia plant builder agent')
doc.multiBuild(story, onFirstPage=page_decorations, onLaterPages=page_decorations)
print('Body PDF written:', OUT_BODY)
